import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Visibility Audit Tools: Compare Evidence, Not Scores",
  description: "Choose between page diagnostics, actual AI-answer observations and first-party outcome measurement. Understand what RankFortune does and does not measure.",
  alternates: { canonical: "/ai-visibility-audit-tools" },
};
const workflows = [
  { name: "Page diagnostics", question: "What does this public URL expose?", evidence: "Dated HTTP and HTML observations, requested path, parser version, source snippets and unknown states.", limit: "Reading robots.txt does not prove real crawler access or indexing. RankFortune currently provides this limited diagnostic scope." },
  { name: "AI-answer observation", question: "Was this brand mentioned or this URL cited?", evidence: "Target product and surface, prompt, language, locale, date, sample repetitions, complete response and visible citation URL.", limit: "Do not infer results from a readiness score, training permissions or a provider API that differs from the consumer product. This is not measured by RankFortune's free scan." },
  { name: "First-party outcomes", question: "Did visibility produce attributable visits or conversions?", evidence: "Analytics source, attribution window, event definition, denominator and missing-data disclosure.", limit: "Referrals, citations and conversions are different measures. RankFortune's free scan does not connect analytics or establish causation." },
];
export default function AiVisibilityAuditToolsPage() {
  return <main className="min-h-screen bg-[#09111f] text-white"><article className="mx-auto max-w-5xl space-y-10 px-5 py-16">
    <Link href="/" className="text-cyan-200 underline">RankFortune</Link>
    <header><p className="text-cyan-200">Tool selection guide · revised September 7, 2026</p><h1 className="mt-4 text-4xl font-semibold sm:text-6xl">Compare the evidence a tool can actually provide.</h1><p className="mt-6 text-lg leading-8 text-slate-300">A page scan, an AI-answer experiment and a conversion report answer different questions. Choose the evidence you need; there is no requirement to finish one before starting another.</p></header>
    <div className="grid gap-5">{workflows.map((item) => <section key={item.name} className="rounded-lg border border-white/10 p-6"><h2 className="text-2xl font-semibold">{item.name}</h2><p className="mt-3 text-cyan-100">{item.question}</p><p className="mt-3 leading-7 text-slate-300">Ask to see: {item.evidence}</p><p className="mt-3 leading-7 text-amber-100">Limit: {item.limit}</p></section>)}</div>
    <section className="space-y-4"><h2 className="text-2xl font-semibold">A practical evaluation checklist</h2><ul className="list-disc space-y-3 pl-5 leading-7 text-slate-300"><li>Use the same URL, page goal and date range for a comparison. Keep excluded private pages and training opt-outs intentional.</li><li>Ask for a sample with failed requests and missing data. Unknown must not become zero visibility, a penalty or an all-clear.</li><li>For citation metrics, request attempted queries N, answer-producing queries A and cited answers C. Report A/N, C/A and C/N separately; zero denominators are N/A.</li><li>Require the rule version and scope on exports. A higher number after a rule change is not measured improvement.</li><li>Verify current commercial scope and fulfillment before purchasing. A checkout option is not proof that monitoring has been delivered.</li></ul></section>
    <section className="rounded-lg border border-cyan-300/20 p-6"><h2 className="text-2xl font-semibold">Where RankFortune fits today</h2><p className="mt-4 leading-7 text-slate-300">The free scan reads one public URL, robots.txt and one sitemap candidate. It reports four separate tracks, with actual AI visibility and business outcomes marked not measured. It does not manufacture FAQ, pricing or comparison-page requirements, or issue a combined GEO score.</p><p className="mt-4"><Link href="/methodology" className="text-cyan-200 underline">Read the versioned method</Link> · <Link href="/sample-report" className="text-cyan-200 underline">See a clearly fictional sample</Link> · <Link href="/#audit" className="text-cyan-200 underline">Run the scan</Link></p></section>
    <section className="space-y-3 text-sm leading-7 text-slate-400"><h2 className="text-xl text-white">Editorial disclosure</h2><p>RankFortune publishes this guide and sells its own reports. This revision replaces unsourced named-product comparisons with an evidence checklist. No current hands-on competitor benchmark, independent reviewer endorsement or price comparison is claimed.</p><p>Official reference: <a className="text-cyan-200 underline" href="https://developers.google.com/search/docs/appearance/ai-features">Google guidance on AI features and your website</a>; <a className="text-cyan-200 underline" href="https://developers.openai.com/api/docs/bots">OpenAI crawler purposes</a>. These describe provider behavior, not an endorsement of RankFortune.</p></section>
  </article></main>;
}
